### ISSUE TITLE
non-primitives shouldn't be allowed

### ISSUE THREAD

**Issue by wtjones** [quiqueporta/simple-value-object#4]
I generally see value objects as a way to represent primitives. This also makes it easier to enforce immutability. 

```
>>> g = Term({'abc':3})
>>> g.hash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/simple_value_object/value_object.py", line 84, in hash
    return hash(self.__class__) and hash(frozenset(self.__dict__.items()))
TypeError: unhashable type: 'dict'
```

You can also do this:

```
>>> g.name['abc'] = 4
>>> g.name
{'abc': 4}
```

**Comment by quiqueporta** [comment]
Fixed here:
https://github.com/quiqueporta/simple-value-object/commit/cf25ea8dee8ad374b9b5c9f93d021e3409c3da77
On 1.0.1 version

**Comment by quiqueporta** [comment]
Thanks :wink:
